modLoader = "kotlinforforge"
loaderVersion = "[5,)"
license = "MIT"

[[mods]]
modId = "processing_chamber"
version = "${version}"
displayName = "Resource Processor"
authors = "GabehEPW"
description = '''
Addon para Cobblemon usando Kotlin, Fabric, NeoForge e Architectury.
'''

[[dependencies.processing_chamber]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.processing_chamber]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.processing_chamber]]
modId = "cobblemon"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
